<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="10" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="102" started-at="2017-04-27T00:07:21Z" finished-at="2017-04-27T00:07:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="102" started-at="2017-04-27T00:07:21Z" finished-at="2017-04-27T00:07:21Z">
      <class name="com.globant.bootcampAutomation.NewTest">
        <test-method status="PASS" signature="PruebaDivisionEscenario1()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaDivisionEscenario1" duration-ms="21" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at com.globant.bootcampAutomation.NewTest.PruebaDivisionEscenario1(NewTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaDivisionEscenario1 -->
        <test-method status="PASS" signature="PruebaDivisionEscenario2()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaDivisionEscenario2" duration-ms="6" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaDivisionEscenario2 -->
        <test-method status="PASS" signature="PruebaMultiplicarEscenario1()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaMultiplicarEscenario1" duration-ms="1" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaMultiplicarEscenario1 -->
        <test-method status="PASS" signature="PruebaMultiplicarEscenario2()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaMultiplicarEscenario2" duration-ms="1" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaMultiplicarEscenario2 -->
        <test-method status="FAIL" signature="PruebaMultiplicarEscenario3()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaMultiplicarEscenario3" duration-ms="1" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4] but found [8373]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4] but found [8373]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.globant.bootcampAutomation.NewTest.PruebaMultiplicarEscenario3(NewTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaMultiplicarEscenario3 -->
        <test-method status="PASS" signature="PruebaNumerosPrimos()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaNumerosPrimos" duration-ms="2" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaNumerosPrimos -->
        <test-method status="PASS" signature="PruebaRestaEscenario1()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaRestaEscenario1" duration-ms="2" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaRestaEscenario1 -->
        <test-method status="PASS" signature="PruebaRestaEscenario2()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaRestaEscenario2" duration-ms="2" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaRestaEscenario2 -->
        <test-method status="PASS" signature="PruebaSumaEscenario1()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaSumaEscenario1" duration-ms="1" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaSumaEscenario1 -->
        <test-method status="PASS" signature="PruebaSumaEscenario2()[pri:0, instance:com.globant.bootcampAutomation.NewTest@7946e1f4]" name="PruebaSumaEscenario2" duration-ms="1" started-at="2017-04-26T19:07:21Z" finished-at="2017-04-26T19:07:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PruebaSumaEscenario2 -->
      </class> <!-- com.globant.bootcampAutomation.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
